APPLICATION ?= threading

BOARD ?= native

# Add extra modules here
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

# Add extended thread information
DEVELHELP ?= 1

RIOTBASE ?= $(CURDIR)/../../RIOT

include $(RIOTBASE)/Makefile.include
